name: flutter_weather_app 
description: A Flutter app that fetches weather
 data from the OpenWeatherMap API and displays
  current temperature, high/low, weather description, and city name.

  

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"  # Add this SDK constraint

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # Use the latest version of the http package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true





